[template]
src = "confd.toml.tmpl"
dest = "/etc/confd/confd.toml"
keys = [
    "/conf/confd/e3w/backend",
    "/conf/confd/e3w/client_cakeys",
    "/conf/confd/e3w/client_cert",
    "/conf/confd/e3w/client_key",
    "/conf/confd/e3w/nodes",
    "/conf/confd/e3w/scheme",
    "/conf/confd/e3w/srv_domain",
    "/conf/confd/e3w/watch",
    "/conf/confd/e3w/onetime",
    "/conf/confd/e3w/interval",
]
#reload_cmd = "supervisorctl restart confd"
